"""New Migration

Revision ID: be5e2b62a62f
Revises: 
Create Date: 2023-06-09 19:01:01.584278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5e2b62a62f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipld',
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('ball_id', sa.Integer(), nullable=False),
    sa.Column('inningNumber', sa.Integer(), nullable=True),
    sa.Column('oversActual', sa.Float(), nullable=True),
    sa.Column('overNumber', sa.Integer(), nullable=True),
    sa.Column('ballNumber', sa.Integer(), nullable=True),
    sa.Column('totalRuns', sa.Integer(), nullable=True),
    sa.Column('batsman', sa.String(), nullable=True),
    sa.Column('bowler', sa.String(), nullable=True),
    sa.Column('batsmanRuns', sa.Integer(), nullable=True),
    sa.Column('isFour', sa.Boolean(), nullable=True),
    sa.Column('isSix', sa.Boolean(), nullable=True),
    sa.Column('isWicket', sa.Boolean(), nullable=True),
    sa.Column('dismissalType', sa.Float(), nullable=True),
    sa.Column('byes', sa.Integer(), nullable=True),
    sa.Column('legbyes', sa.Integer(), nullable=True),
    sa.Column('wides', sa.Integer(), nullable=True),
    sa.Column('noballs', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('Comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ball_id')
    )
    op.create_index(op.f('ix_ipld_ball_id'), 'ipld', ['ball_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipld_ball_id'), table_name='ipld')
    op.drop_table('ipld')
    # ### end Alembic commands ###
